# Generated by Django 5.0.1 on 2024-02-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
