# Generated by Django 5.0.1 on 2024-02-03 16:31

import apps.device_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_system', '0005_devicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='status',
            field=models.CharField(choices=[(apps.device_system.models.DeviceLog.LogStatus['NOT_RETURNED'], 'Not Returned'), (apps.device_system.models.DeviceLog.LogStatus['RETURNED'], 'Returned')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
