# Generated by Django 5.0.1 on 2024-02-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_system', '0006_devicelog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Not Returned', 'Not Returned')], default='Not Returned', max_length=15),
        ),
    ]
