# Generated by Django 5.0.1 on 2024-02-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_system', '0007_alter_devicelog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('Fair', 'Fair'), ('Good', 'Good'), ('Excellence', 'Excellence'), ('Bad', 'Bad'), ('Damage', 'Damage')], max_length=15, null=True),
        ),
    ]
